name: snippy   
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - vt==2015.11.10
  - snippy==4.05
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - spades
  - sra-tools
  - fastqc
  - biopython
